Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/precise64"
  config.vm.provision "shell", path: "project/project/ops/dev/scripts/setup.sh"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network :forwarded_port, guest: 8000, host: 8000

  # Update <username> below with your Atlas username
  config.push.define "atlas" do |push|
    push.app = "<username>/django-app"
  end

end